server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    instance:
      instance-id: gateway-9527.com #自定义服务名称信息
      #prefer-ip-address: true #访问路径可以显示IP地址


info:
  app.name: molv-microservicecloud
  company.name: www.molv.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


zuul:
  prefix: /molv
  #忽略所有原真实服务名
  ignored-services: "*"
  routes:
    #微服务代理名称key-value
    #原http://myzuul.com:9527/microservicecloud-dept/dept/get/2
    #http://myzuul.com:9527/molv/mydept/dept/get/2
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**